version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=py_test
      - MYSQL_ROOT_PASSWORD=root

  mysite:
    build: .
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        python manage.py runserver 0.0.0.0:8088 --insecure
#        python manage.py migrate

#    command: uwsgi --http :8088 --enable-threads --processes 4 --threads 2 --wsgi-file /usr/src/app/mysite/wsgi.py
    volumes:
      - .:/usr/src/app
    ports:
      - 8088:8088
    depends_on:
      - db



