# Generated by Django 2.1.5 on 2019-01-19 03:32

from django.db import migrations, models
import djangoUeditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaobing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createTime',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='isShow',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='是否显示指令说明'),
        ),
        migrations.AlterField(
            model_name='order',
            name='isShowOrder',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='是否显示该条指令'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=99, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDescription',
            field=djangoUeditor.models.UEditorField(verbose_name='指令说明'),
        ),
        migrations.AlterField(
            model_name='order',
            name='typeDescription',
            field=djangoUeditor.models.UEditorField(verbose_name='类型说明'),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='createTime',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='number',
            field=models.IntegerField(default=99, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='typeName',
            field=djangoUeditor.models.UEditorField(verbose_name='类型名称'),
        ),
    ]
